# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics

on:
  schedule:
    - { cron: '0 0 * * *' }
  workflow_dispatch:
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - id: self
        uses: lowlighter/metrics@v4
        with:
          filename: metrics.self.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
      - id: faker
        uses: lowlighter/metrics@v4
        with:
          filename: metrics.faker.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          user: faker-js
