# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics

on:
  schedule:
    - { cron: '0 0 * * *' }
  workflow_dispatch:
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: self
        uses: lowlighter/metrics@65836723097537a54cd8eb90f61839426b4266b6 # v3.34
        with:
          filename: metrics.self.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          base_indepth: yes
          repositories_affiliations: ['owner', 'collaborator']
      - name: Current year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          plugin_calendar: yes
          plugin_calendar_limit: 0
      - name: faker
        uses: lowlighter/metrics@65836723097537a54cd8eb90f61839426b4266b6 # v3.34
        with:
          filename: metrics.faker.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          plugin_repositories: yes
          plugin_repositories_featured: faker-js/faker
